### ISSUE TITLE
theSpawn v2.0.0 | TO-DO list & release date

### ISSUE THREAD

**Issue by supercrafter333** [supercrafter333/theSpawn#69]
<u>**Planned Features**</u>

- [X] reformat huge parts of theSpawn's codes, files and file-structure
 - [X] add support for PM5 (& PM4 as a hybrid version)
 - [X] add support for PHP 8.1 (remove support for PHP 8.0 or lower)
 - [X] add player-warps
 - [X] add missing forms for: aliases, tpa's, player-warps
 - [X] every features of theSpawn can be enabled and disabled (also spawns, hubs, ...)
 - [X] smaller files for warps and homes
 - [X] uniform storage format for locations
 - [X] location-class as default class for locations of spawns, hubs, warps, homes, player-warps
 - [ ] add toast-notifications for special alerts (e.g. tpa-requests)

All completed features can be found in the [PM5-development class](https://github.com/supercrafter333/theSpawn/tree/PM5-development). Some of the features may not be committed yet.

<u>**Release Date**</u>
The release of theSpawn v2.0.0 is scheduled for January 7th or 14th, 2023.
